version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: petclinic-db-postgres-prod
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    ports:
      - "5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: prod
    container_name: petclinic-app
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-volume:


